export class QuestSystem {
  constructor(state, inventory, ui) { this.state = state; this.inventory = inventory; this.ui = ui; }
  q() { return this.state.get().quests || {}; }
  setQuest(key, value) { this.state.set({ quests: { ...this.q(), [key]: { ...(this.q()[key] || {}), ...value } } }); }
  reward(key) { if (key && this.q()[key]?.completed) return false; if (key) this.setQuest(key, { completed: true }); this.state.addMoney(20); this.state.set({ levelPoints: (this.state.get().levelPoints || 0) + 20 }); this.ui.updateMissions(); return true; }
  handle(kind) {
    if (kind === 'shepherd' || kind === 'camel') return this.shepherd(kind);
    if (kind === 'archaeologist' || kind === 'ruins') return this.pair('archaeology', kind, 'الباحثة الأثرية', 'الآثار', 'ابحث عن الآثار ثم ارجع للباحثة.', 'وجدت الآثار. ارجع للباحثة.', 'أخبرت الباحثة عن مكان الآثار.');
    if (kind === 'herbalist') return this.collect('rarePlants', 'rarePlant', 'العطارة', 'ابحث عن نبتة نادرة واحدة ثم ارجع.', 'سلمت النبتة النادرة للعطارة.');
    if (kind === 'rarePlant') { if (!this.q().rarePlants?.completed && !this.inventory.items().find(i => i.id === 'rarePlant')) this.inventory.add({ id:'rarePlant', name:'نبتة نادرة', type:'quest', img:'All-Pic/npc/q34.png' }); return this.ui.openText('نبتة نادرة', 'تمت إضافة النبتة إلى الحقيبة. ارجع للعطارة.'); }
    if (kind === 'messenger') return this.delivery('messageQuest','message_note','صاحب الرسالة','خذ الرسالة إلى صديقه.','أخذت الرسالة. ابحث عن الصديق.');
    if (kind === 'messengerFriend') return this.finishDelivery('messageQuest','message_note','صديق صاحب الرسالة','وصلت الرسالة إلى الصديق.');
    if (kind === 'fireMan') return this.delivery('fireQuest','water_bucket','صاحب الخيمة','ابحث عن البئر وخذ الماء لإطفاء النار.','خذ الماء من البئر ثم ارجع.');
    if (kind === 'well') { if (!this.q().fireQuest?.completed && !this.inventory.items().find(i => i.id === 'water_bucket')) this.inventory.add({ id:'water_bucket', name:'سطل ماء', type:'quest', img:'All-Pic/npc/q23.png' }); return this.ui.openText('البئر', 'تمت تعبئة الماء. ارجع إلى صاحب الخيمة.'); }
    if (kind === 'dateWoman') return this.finishDelivery('dateQuest','dates','صاحبة الضيوف','تم تسليم التمر.');
    if (kind === 'palm') { if (!this.q().dateQuest?.completed && !this.inventory.items().find(i => i.id === 'dates')) this.inventory.add({ id:'dates', name:'تمر', type:'quest', img:'All-Pic/npc/q31.png' }); return this.ui.openText('النخلة', 'تمت إضافة التمر إلى الحقيبة. ارجع إلى صاحبة البيت.'); }
    return this.ui.openText('معلومة', 'هذا المكان مرتبط بمهمة.');
  }
  pair(key, kind, giver, target, start, found, done) { const q = this.q()[key] || {}; if (q.completed) return this.ui.openText(giver, 'أنت أكملت هذه المهمة خلاص.'); if (kind === 'ruins') { this.setQuest(key,{foundTarget:true}); return this.ui.openText(target, found); } if (q.foundTarget) { this.reward(key); return this.ui.openText(giver, done + ' حصلت على 20 ريال و20 نقطة.'); } this.setQuest(key,{started:true}); return this.ui.openText(giver, start); }
  collect(key, itemId, title, start, done) { if (this.q()[key]?.completed) return this.ui.openText(title, 'أنت أكملت هذه المهمة خلاص.'); const item = this.inventory.items().find(i => i.id === itemId); if (item) { this.inventory.remove(itemId); this.reward(key); return this.ui.openText(title, done + ' حصلت على 20 ريال و20 نقطة.'); } this.setQuest(key,{started:true}); return this.ui.openText(title, start); }
  delivery(key, itemId, title, start, carrying) { if (this.q()[key]?.completed) return this.ui.openText(title, 'أنت أكملت هذه المهمة خلاص.'); if (!this.inventory.items().find(i => i.id === itemId)) this.inventory.add({ id:itemId, name:title.includes('رسالة')?'رسالة':'عنصر مهمة', type:'quest', img:itemId==='message_note'?'All-Pic/npc/q30.png':'All-Pic/npc/q23.png' }); this.setQuest(key,{started:true}); return this.ui.openText(title, carrying || start); }
  finishDelivery(key, itemId, title, done) { if (this.q()[key]?.completed) return this.ui.openText(title, 'أنت أكملت هذه المهمة خلاص.'); if (this.inventory.items().find(i => i.id === itemId)) { this.inventory.remove(itemId); this.reward(key); return this.ui.openText(title, done + ' حصلت على 20 ريال و20 نقطة.'); } this.setQuest(key,{started:true}); return this.ui.openText(title, 'أحضر عنصر المهمة أولاً.'); }
  shepherd(kind) { const q = this.q().shepherdCamel || {}; if (q.completed) return this.ui.openText('الراعي', 'أنت أكملت هذه المهمة خلاص.'); if (kind === 'camel') { if (!this.inventory.items().find(i => i.id === 'camel')) this.inventory.add({ id:'camel', name:'الجمل الضائع', type:'quest', img:'All-Pic/npc/q33.png' }); this.setQuest('shepherdCamel',{foundCamel:true}); return this.ui.openText('الجمل الضائع','وجدت الجمل. ارجع إلى الراعي.'); } if (this.inventory.items().find(i => i.id === 'camel') || q.foundCamel) { this.inventory.remove('camel'); this.reward('shepherdCamel'); return this.ui.openText('الراعي','رجعت الجمل للراعي، حصلت على 20 ريال و20 نقطة.'); } this.setQuest('shepherdCamel',{foundShepherd:true}); return this.ui.openText('الراعي','الراعي يبحث عن جمله الضائع. ابحث عن الجمل ثم ارجع له.'); }
}
